/// Generated by spider on 2020-05-29 21:59:54.641155

import 'dart:io';

import 'package:flutterPortfolio/resources/images.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('images assets test', () {
    expect(true, File(Images.support).existsSync());
    expect(true, File(Images.gitHubDart).existsSync());
    expect(true, File(Images.adobeXd).existsSync());
    expect(true, File(Images.mail).existsSync());
    expect(true, File(Images.instagram).existsSync());
    expect(true, File(Images.github).existsSync());
    expect(true, File(Images.firebase).existsSync());
    expect(true, File(Images.githubLogo).existsSync());
    expect(true, File(Images.background).existsSync());
    expect(true, File(Images.medium).existsSync());
    expect(true, File(Images.gitHubAndroid).existsSync());
    expect(true, File(Images.gitHubiOs).existsSync());
    expect(true, File(Images.twitter).existsSync());
    expect(true, File(Images.swift).existsSync());
    expect(true, File(Images.linkedin).existsSync());
    expect(true, File(Images.profile).existsSync());
    expect(true, File(Images.location).existsSync());
    expect(true, File(Images.phone).existsSync());
  });
}
