/// Generated by spider on 2023-03-31 11:57:39.625260

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:flutterPortfolio/resources/images.dart';

void main() {
  test('images assets test', () {
    expect(File(Images.adobeXd).existsSync(), true);
    expect(File(Images.android).existsSync(), true);
    expect(File(Images.aws).existsSync(), true);
    expect(File(Images.background).existsSync(), true);
    expect(File(Images.firebase).existsSync(), true);
    expect(File(Images.gitHubAndroid).existsSync(), true);
    expect(File(Images.gitHubDart).existsSync(), true);
    expect(File(Images.gitHubiOs).existsSync(), true);
    expect(File(Images.github).existsSync(), true);
    expect(File(Images.githubLogo).existsSync(), true);
    expect(File(Images.instagram).existsSync(), true);
    expect(File(Images.linkedin).existsSync(), true);
    expect(File(Images.location).existsSync(), true);
    expect(File(Images.mail).existsSync(), true);
    expect(File(Images.medium).existsSync(), true);
    expect(File(Images.nodejs).existsSync(), true);
    expect(File(Images.phone).existsSync(), true);
    expect(File(Images.playstore).existsSync(), true);
    expect(File(Images.profile).existsSync(), true);
    expect(File(Images.serverless).existsSync(), true);
    expect(File(Images.support).existsSync(), true);
    expect(File(Images.swift).existsSync(), true);
    expect(File(Images.twitter).existsSync(), true);
    expect(File(Images.typescript).existsSync(), true);
  });
}
