// Generated by spider on 2023-03-31 11:57:39.554438

class Images {
  Images._();

  static const String adobeXd = 'assets/images/adobeXD.png';
  static const String android = 'assets/images/android.png';
  static const String aws = 'assets/images/aws.webp';
  static const String background = 'assets/images/background.jpg';
  static const String firebase = 'assets/images/firebase.png';
  static const String gitHubAndroid = 'assets/images/gitHubAndroid.png';
  static const String gitHubDart = 'assets/images/gitHubDart.png';
  static const String gitHubiOs = 'assets/images/gitHubiOS.png';
  static const String github = 'assets/images/github.png';
  static const String githubLogo = 'assets/images/github_logo.png';
  static const String instagram = 'assets/images/instagram.png';
  static const String linkedin = 'assets/images/linkedin.png';
  static const String location = 'assets/images/location.png';
  static const String mail = 'assets/images/mail.png';
  static const String medium = 'assets/images/medium.png';
  static const String nodejs = 'assets/images/nodejs.png';
  static const String phone = 'assets/images/phone.png';
  static const String playstore = 'assets/images/playstore.png';
  static const String profile = 'assets/images/profile.jpg';
  static const String serverless = 'assets/images/serverless.png';
  static const String support = 'assets/images/support.png';
  static const String swift = 'assets/images/swift.png';
  static const String twitter = 'assets/images/twitter.png';
  static const String typescript = 'assets/images/typescript.png';
}
